spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - name: AuthFilter

            - id: chat-service
              uri: lb://chat-service
              predicates:
                - Path=/api/rooms/**, /api/messages/**, /api/members/**
              filters:
                - name: AuthFilter

            - id: ws-service
              uri: lb://ws-service
              predicates:
                - Path=/ws/**
              filters:
                - name: AuthFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: true
    discovery:
      client:
        simple:
          instances:
            user-service:
              - uri: http://localhost:4001
            chat-service:
              - uri: http://localhost:4000
            ws-service:
              - uri: http://localhost:4002
              - uri: http://localhost:4003


jwt:
  secret: youraccesstokensecretbase64encoded256bityouraccesstokensecretbase64encoded256bityouraccesstokensecretbase64encoded256bit
gateway:
  internal-secret: ${INTERNAL_SECRET:telegramsecretkey}

# Public endpoints ? kh�ng c?n JWT
public:
  endpoints:
    - /api/users/auth/login
    - /api/users/auth/register
    - /api/users/auth/refresh
    - /api/users/auth/google
    - /api/users/auth/logout
    - /ws
server:
  port: 3000